spring:
  data:
    mongodb:
#      uri: mongodb://easewise:easewise@192.168.2.100:27017/easewise?authSource=easewise&ssl=false
      host: localhost
      port: 27017
      database: jeddit_test

#logging:
#  level:
#    root: DEBUG