spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: jeddit_test
  r2dbc:
    driver: postgres
    host: 192.168.2.100
    port: 5431
    database: jeddit
    username: postgres
    password: mzh888888

logging:
  level:
    web: debug
