spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: jeddit_test
#  r2dbc:
#    url: r2dbc:postgresql://192.168.2.100/test
#    username: postgres
#    password: mzh888888
#    initialization-mode: always

logging:
  level:
    web: debug
